= Red Hat OpenShift Container Platform 4: Baremetal UPI Installation
:navtitle: Home

[IMPORTANT]
The lab runs on the one of the Red Hat internal infrastructures called PSI.
This lab is accessible to Red Hat Employees only.

== Introduction

Course Title: Red Hat OpenShift Container Platform 4 - Baremetal UPI Installation

Description: This hands-on lab training provides you with hands on lab to install Red Hat OpenShift Container Platform 4 environment using User-provisioned infrastructre (UPI) method on baremetal.

Duration: 1 hour

== Objectives

On completing this course, you should be able to install Red Hat OpenShift Container Platform 4 using User-provisioned infrastructre (UPI) on baremetal.

== Prerequisites

This course assumes that you have the following prior experience:

* A Red Hat Certified System Administrator (RHCSA) or have equivalent experience administrating Red Hat Enterprise Linux 8 or 9.
* A Red Hat Certified Specialist in OpenShift Administration on version 4 or have equivalent experience.
