= Lab (1 of 2)

== Lab prerequisites

. Use the ssh command given the NovelloShell output to login to the `provision` and `lb` virtual machines.
+
.Sample Output
[source,texinfo,subs="attributes"]
----
laptop@user:~ $ ssh -i ~/.ssh/pntae_training_key cloud-user@10.0.108.202
...
...
[cloud-user@provision ~]$

You can ssh to `lb` virtual machine from the `provision` virtual machine.

[cloud-user@provision ~]$ ssh lb
...
...
[cloud-user@lb ~]$
----

. Ensure the `provision` and `lb` virtual machines are unregistered and unsubscribed.
+
[source,sh,role=execute]
----
sudo subscription-manager unregister; sudo subscription-manager remove --all; sudo subscription-manager clean
----
+
.Sample Output
[source,texinfo,subs="attributes"]
----
[cloud-user@provision ~]$ sudo subscription-manager unregister; sudo subscription-manager remove --all; sudo subscription-manager clean
This system is currently not registered.
0 subscriptions removed from this system.
All local data removed
----

. Now, register and subscribe the `provision` and `lb`virtual machines with your customer portal (access.redhat.com) credentials.
+
[source,sh,role=execute]
----
sudo subscription-manager register
----
+
.Sample Output
[source,texinfo,subs="attributes"]
----
Registering to: subscription.rhsm.redhat.com:443/subscription
Username:
Password:
The system has been registered with ID: bc91d274-84b4-4175-a4df-xxyyzz
The registered system name is: provision.example.com

Registering to: subscription.rhsm.redhat.com:443/subscription
Username:
Password:
The system has been registered with ID: bc91d274-84b4-4175-a4df-xxyyzz
The registered system name is: lb.example.com
----

. Additional lab information:

.. The connection is already modified by executing following commands:
+
.Sample Output
[source,texinfo,subs="attributes"]
----
$ sudo nmcli connection modify "System eth1" connection.zone internal
$ sudo nmcli connection modify "System eth0" connection.zone external
----

.. You can verify the same by running following command:
+
.Sample Output
[source,texinfo,subs="attributes"]
----
$ sudo firewall-cmd --list-all --zone=internal
$ sudo firewall-cmd --list-all --zone=external
----

. All required configuration files are in `/tmp` directory of `provision` and `lb` virtual machines.

. The RHCOS live image `rhcos-418.94.202501221327-0-live.x86_64.iso` is already downloaded and attached to all nodes (bootstarap, master and worker) as `rhcos-418.94.202501221327-0-live.x86_64-pntae`.

=== Load Balancer Virtual Machine Setup

. Make sure PSI's DNS entries are removed.
You will find this information in reference material.

. Make sure required packages are installed on `lb` machine:
+
.Sample Output
[source,texinfo,subs="attributes"]
----
jq
ipmitool
firewalld
tmux
podman
vim
wget
telnet
curl
haproxy
----

. You need to configure the firewall rules as per the RHOCP 4.18 requirements.

. Reference configuration files for HA-proxy server are placed in `lb` virtual machine's `/tmp` directory.

=== Provision Virtual Machine Setup

. Make sure PSI's DNS entries are removed.
You will find this information in reference material.

. Make sure required packages are installed on `provision` machine:
+
.Sample Output
[source,texinfo,subs="attributes"]
----
jq
ipmitool
dhcp-server
bind
bind-utils
firewalld
httpd
httpd-tools
tmux
podman
telnet
----

. Create `lab-user` on `provision` machine.
Make sure `lab-user` has sudo privileges.

. Reference configuration files for DNS and DHCP server are placed in `provision` machine's `/tmp` directory.
Configure the `provision` machine as DNS and DHCP server.

. Configure httpd server on `provision` virtual machine to host the ignition configs.

. You need to configure the firewall rules as per the RHOCP 4.18 requirements.

. For oc client and openshift install binary, use this the URL - https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.18.11/openshift-client-linux.tar.gz and https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.18.11/openshift-install-linux.tar.gz

. Other configuration files such as `install.conf` and additional custom command files is also placed under `provision` machine's `/tmp` directory.

. Make sure `core` user is able to ssh nodes (worker, master and bootstrap) using `lab-user` SSH keys.
